#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # need to strip @ from user input....
    screen_name = (sys.argv[1]).lstrip("@")
    
    # need to create sys.exit for return of None.....
    handle = helpers.get_user_timeline(screen_name, 50)
    if handle == None:
        sys.exit("Could not retrieve keys for {}".format(sys.argv[1]))
    # print(handle) ...only for testing...
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # analyze tweets
    for tweet in handle:
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(" 1 {}".format(tweet), "green"))
        elif score < 0.0:
            print(colored("-1 {}".format(tweet), "red"))
        else:
            print(colored(" 0 {}".format(tweet), "yellow"))
    
    
if __name__ == "__main__":
    main()
